apiVersion: v1
kind: Service
metadata:
    name: "accelerateshopping-a57a"
    labels:
        app: "accelerateshopping-a57a"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "accelerateshopping-a57a"